### PR TITLE
Fix #93 - deprecated import from flask.ext.sqlalchemy

### LINKED ISSUE #93: Deprecated import from flask.ext.sqlalchemy
This import is throwing a deprecation warning with Flask 0.11

    flask_debugtoolbar/panels/sqlalchemy.py:2:    from flask.ext.sqlalchemy import get_debug_queries, SQLAlchemy

### PR DESCRIPTION
**Pull request by mlenzen**

### CODE REVIEW

**Comment by edouardberthe** [comment]
👍

**Comment by edouardberthe** [comment]
And your Issue : https://github.com/mgood/flask-debugtoolbar/issues/93

**Comment by iurisilvio** [comment]
That's true! :+1:

I didn't checked for other pull requests.

**Comment by jeffwidman** [comment]
Thanks!

**Comment by roganov** [comment]
Do you plan on rolling a release with this patch?

**Comment by jeffwidman** [comment]
Yes, I just have been on vacation a good chunk of July/August so had minimal time outside of normal commitments.

**Comment by ncrocfer** [comment]
Do you have any news about this release please ? The 0.10.0 still has the old import.

**Comment by rlam3** [comment]
Is there any reason why this hasn't been released yet? It's been over half a year now....

**Comment by jeffwidman** [comment]
I'm not the owner, but I do have pypi rights, and I keep meaning to cut a new release, just haven't gotten to it yet...

**Pull request merged**
