### PR TITLE
Remove deprecated `flask.ext.*` magic imports.

### PR DESCRIPTION
**Pull request by iurisilvio**

### CODE REVIEW

**Comment by jeffwidman** [comment]
Partial dupe of #94 although this should also be merged because it fixes some more stuff

**Comment by edouardberthe** [comment]
Please could someone merge it, this message is really annoying!

**Comment by jeffwidman** [comment]
I was just added as a collaborator, so I went ahead and merged this. Thanks!

**Comment by Jaza** [comment]
Thanks for merging. Can you also release a new version, please? So we can stay on a stable release and not see the deprecation warnings with Flask 0.11.x.

**Comment by jeffwidman** [comment]
I keep meaning to do this, just haven't had time yet

**Pull request merged**
